name: Daily Scrape

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 12:00am EST (4am UTC)
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        run: node scrape.mjs

      - name: Commit updated ice_times.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ice_times.json
          git commit -m "Update ice times [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
