name: Daily Scrape

on:
  schedule:
    - cron: '0 4 * * *'  # 12:00 AM EST
  workflow_dispatch:
    inputs:
      date: 
        description: 'optional date to scrape (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # disable default token

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        run: node scrape.mjs ${{ github.event.inputs.date }}

      - name: Commit and push updated ice_times.json
  
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main

          git add ice_times.json
          git diff --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update ice_times.json [auto]"
          git push https://x-access-token:${GH_PAT}@github.com/eloisedev/tendy main
