name: Daily Scrape

on:
  schedule:
    - cron: '0 4 * * *'  # 12:00 AM EST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # disable default token

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        run: node scrape.mjs

      - name: Commit and push updated ice_times.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "🔒 Testing token access..."
          git ls-remote https://x-access-token:${GH_PAT}@github.com/eloisedev/tendy || exit 1

          echo "🔧 Setting up Git"
          git config --global user.name "github-actions[bot]"
          git config --global user.email github-actions@github.com

          echo "🔃 Fetching latest main"
          git fetch origin
          git reset --hard origin/main

          echo "📦 Committing changes"
          git add ice_times.json
          git commit -m "Update ice times [auto]" || echo "No changes to commit"

          echo "🚀 Pushing to main"
          git push https://x-access-token:${GH_PAT}@github.com/eloisedev/tendy HEAD:main

